annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: cattle-ui-plugin-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux, windows
  catalog.cattle.io/scope: management
  catalog.cattle.io/ui-component: plugins
  catalog.cattle.io/display-name: VergeOS Node Driver
  catalog.cattle.io/kube-version: '>= 1.16.0-0'
  catalog.cattle.io/rancher-version: '>= 2.10.0-0'
  catalog.cattle.io/ui-extensions-version: '>= 3.0.0 < 4.0.0'
apiVersion: v2
appVersion: 0.2.0
description: VergeOS Node Driver UI for Rancher
name: vergeos
type: application
version: 0.2.0
